language: node_js
node_js:
- '10'
script: npm run build
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: firebase
  project: qube-timer
  message: TravisCI triggered deployment
  token:
    secure: a2zrdNJCG5AKMKpz2VpFBQYHc1649Cl65KsomOQvj+w24r8KaaltD+LLG58FhPSSqS/LwRpdTQpxPV+8b1+j6XjxLVIxxet+1IA7nXTd7KVHxnIv5VNftHyt1ZHnBfyd5apRz0tUDVnQ7F7YjaAKfbvSwlKMg/llDliJ4yBY+7i3zcJZ3T6Mxa6TfTMKGOxFLNhyx/uuLO1YSjl1tpcZoNnoO3JG2kRiggl7dNN+P0rAzxvVYysNAZbK0tSNSdRcxXcl+F/ok517xJpjo8NU1FDDZifs83afImmFYRG14ZJjH5HzovnmOhXbVzetNlZFz+k8/2ix4f6BsH0qNbFz0uIwb67KFpiA7hlPJKEXbYpb5jX0Trop+fgAYXXEWSEUN56g9Hvpca+ibAths8P6J+8FsQ114DWZeSw+H0PH+B5v7ZA4NrD1WGkWCbryYlT1aH9Vtlt20gid+FoUGWfq7wmxIYUBz/+qjDq+9x7/DXCtD5jHNjHARBnQVTFaQF4DmHrBmbmCUPXTMDySTXpRfYm2VqQa6bOTCC4nZaDLA763FWs0AzsFon5yxsNTBJBIlIaVMtD87Ds9aNLVNElxZgmUSPUG9CUtRWD+uJb++otXWj8bthNQ5pv/w3ePO1ngZyE8yUXTPvr0aCkUq3EEE+JRpJZd7DrxXaOUoQrEsTU=
